services:
  mysql:
    container_name: warehouse-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse
      MYSQL_USER: warehouse
      MYSQL_PASSWORD: warehouse
    ports:
      - "3307:3306"
    volumes:
      - warehouse-mysql:/var/lib/mysql
    networks:
      - warehouse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "warehouse", "-pwarehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: warehouse-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Override database connection for Docker environment
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/warehouse
      SPRING_DATASOURCE_USERNAME: warehouse
      SPRING_DATASOURCE_PASSWORD: warehouse
    networks:
      - warehouse-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

networks:
  warehouse-network:
    driver: bridge

volumes:
  warehouse-mysql:
