server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: warehouse-demo

  datasource:
    url: jdbc:mysql://localhost:3307/warehouse
    username: warehouse
    password: warehouse
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: mySecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmRequirement12345
  expiration: 86400000 # 24 hours in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,scheduledtasks
  endpoint:
    health:
      show-details: always

# Logging is configured via log4j2.xml

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    default-models-expand-depth: 3
    default-model-rendering: model
    display-request-duration: true
    doc-expansion: none